title: "HINF 5016: Natural Language Processing in Health"
description: "Jan. 11, 2023 - April 19, 2022, 5:00-8:00 pm East Time on Wednesdays | 
              1300 York Ave. (C-200)"
theme: jekyll-theme-cayman
